### ISSUE TITLE
Keyring error

### ISSUE THREAD

**Issue by hamlitbass** [PrOF-kk/rainmeter-gkeep#6]
Hey there, i'm fairly certain everything is installed properly. but I keep getting this error.

Traceback (most recent call last):
  File "C:\Users\Hamnando\Documents\Rainmeter\Skins\Keep\Keep.py", line 9, in <module>
    import keyring
ModuleNotFoundError: No module named 'keyring'

I don't have 2FA on my google account which could be why perhaps? I'm reluctant to turn it on.

**Comment by PrOF-kk** [comment]
The `keyring` library is what's missing, I forgot to add it to the requirements...  
`pip install keyring` should do the trick

**Comment by PrOF-kk** [comment]
Fixed in https://github.com/PrOF-kk/rainmeter-gkeep/commit/73a78e2205b35f5af9735c2c36f4c5b00e5e1de5
