### ISSUE TITLE
i'm gettining errors here it is  

### ISSUE THREAD

**Issue by theanupamkumar1** [PrOF-kk/rainmeter-gkeep#7]
![Screenshot (205)](https://github.com/PrOF-kk/rainmeter-gkeep/assets/62919574/82a3fc71-9a43-43c5-8bd2-5fd3f758dba4)

what should i do

**Comment by PrOF-kk** [comment]
Hello, you're likely trying to use this skin with a *TODO List* instead of a plain note, which isn't supported.
TODO Lists are the ones with a checkbox on the left ( ☐ )

**Comment by theanupamkumar1** [comment]
yes, you are right, that's what I'm trying to do.  Isn't there any solution to have my Google Keep as a rainmeter widget?

**Comment by theanupamkumar1** [comment]
what is the use of that "upload" icon and that "choose note" option on right click "?

**Comment by PrOF-kk** [comment]
The "upload" icon lets you make changes to the note. Edit the note, press the button and it will get uploaded to the Google Keep servers
