### ISSUE TITLE
Error messages in protocol and empty note

### ISSUE THREAD

**Issue by maaaaaajin** [PrOF-kk/rainmeter-gkeep#8]
I started the skin and got an empty black bar under the two buttons. When i checked the protocol in Rainmeter i saw two error messages: 
Error 103: Cannot start program: python (Keep\Keep.ini - [KeepGet])
!UpdateMeasure: [OutputViewer] not found (Keep\Keep.ini)
does anybody know a solution?

**Comment by PrOF-kk** [comment]
Did you fix this on your own or was this closed by mistake?

**Comment by maaaaaajin** [comment]
I added the path of python.exe to the user-variables but i dont know if this solved it or if it solved itsself after a pc restart. So no, wasn't a mistake. Now the start of python works but the login problem sticks.
